@startuml

:Set-up of game (not included);

start

repeat

if (Upgrade shop full?) then (Yes)
:Replace upgrade cards;
else (No)
:Fill missing cards;
endif

:**Play programming phase**
- Draw programming cards
- Place programming cards
- Discard remaining cards;

repeat
repeat
:Next player moves robot;
if (Robot moves into other robot?) then (Yes)
:Push robot;
else (No)
endif

repeat while (Have all robots used 1 programming card) is (No)
-> Yes;

:Activate board;
if (Robot in line of sigth of laser?) then (Yes)
:- Take damage
- Draw damage card
- Shuffle card in programming deck;
else (No);
endif

repeat while (Have all robots used all programming cards?) is (No)
-> Yes;
repeat while (Has game ended?) is (No)
-> Yes;
stop

@enduml