@startuml
hide empty members



class RoboRally {
}
package player {
	class Player {
		- int energyCubes
	}
	class Robot {

	}
	
}



package deck {
	class Deck {
	}
	abstract class Cards{
		
	}
	class ProgrammingCards{
		
	}
	class UpgradeCards{
		
	}
	class DamageCards{
		
	}
}


package field {

	abstract class Field {
		- int x
		- int y
	}
	class StandardField {

	}
	class WallField {

	}


	class CheckPoint {

	}

}



Player <-- Robot
RoboRally <-left- Player
RoboRally <-down- Deck
RoboRally <-up- Field
Field <|-left- CheckPoint
Field <|-up- StandardField
Field <|-right- WallField
Deck *-- Cards
Cards <|-- ProgrammingCards
Cards <|-up- UpgradeCards
Cards <|-right- DamageCards

@enduml